version: '2.4'

services:

  proxy:
    image: nginx:1.16-alpine
    environment:
      PWA_DOC_ROOT: $PROJECT_PATH/vigisade-pwa/dist
    entrypoint: /usr/local/bin/entrypoint.sh
    command: nginx -g 'daemon off;'
    volumes:
      - $PROJECT_PATH/.docker/proxy/etc/nginx/conf.d:/etc/nginx/conf.d:ro
      - $PROJECT_PATH/.docker/proxy/usr/local/bin/entrypoint.sh:/usr/local/bin/entrypoint.sh:ro
      - $PROJECT_PATH/vigisade-pwa/dist:$PROJECT_PATH/vigisade-pwa/dist:ro
    depends_on:
      - php
  
  # Apache + PHP.
  php:
    image: $IMAGE_WEB_PHP
    environment:
      WWW_UID: $USER_ID
      WWW_GID: $GROUP_ID
      WWW_HOME: $USER_HOME
      WWW_DOCROOT: $PROJECT_PATH/vigisade-web/public

      DATABASE_URL: mysql://$DB_USER:$DB_PWD@db:3306/$DB_NAME
      AUTH_PASSPHRASE: r2FM3cws

    volumes:
      - $USER_HOME/.ssh:/root/.ssh:ro
      - $USER_HOME/.ssh:/var/web/.ssh:$VOLUME_OPTION
      - $USER_HOME/.ssh:$USER_HOME/.ssh:$VOLUME_OPTION
      - $USER_HOME/.composer:$USER_HOME/.composer:$VOLUME_OPTION
      - $PROJECT_PATH/vigisade-web:$PROJECT_PATH/vigisade-web:$VOLUME_OPTION
    working_dir: $PROJECT_PATH/vigisade-web

  # Database.
  db:
    image: mysql:5.7
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
      MYSQL_ROOT_PASSWORD: ''

      MYSQL_DATABASE: $DB_NAME
      MYSQL_USER: $DB_USER
      MYSQL_PASSWORD: $DB_PWD

    volumes:
      - mysql:/var/lib/mysql

volumes:
  mysql:

networks:
  default:
    ipam:
      config:
        - subnet: ${SUBNET_DEFAULT}

# vim: ts=2 sts=2 sw=2 et:
