version: '2.4'

services:

  php:
    logging: &logging
      driver: gelf
      options:
        gelf-address: "udp://$GELF_IP:12201"
        tag: ${COMPOSE_PROJECT_NAME}${PROXY_VIRTUAL_HOST_SUFFIX}

  db:
     logging: *logging

# vim: ts=2 sts=2 sw=2 et:
