version: '2.4'

services:

  # Apache + PHP.
  php:
    image: $IMAGE_WEB_PHP
    environment:
      WWW_UID: $USER_ID
      WWW_GID: $GROUP_ID
      WWW_HOME: $USER_HOME
      WWW_DOCROOT: $PROJECT_PATH/vigisade-web/public

      DATABASE_URL: mysql://$DB_USER:$DB_PWD@db:3306/$DB_NAME

    volumes:
      - $USER_HOME/.ssh:/root/.ssh:ro
      - $USER_HOME/.ssh:/var/web/.ssh
      - $USER_HOME/.ssh:$USER_HOME/.ssh
      - $USER_HOME/.composer:$USER_HOME/.composer
      - $PROJECT_PATH/vigisade-web:$PROJECT_PATH/vigisade-web
    working_dir: $PROJECT_PATH/vigisade-web

  # Database.
  db:
    image: mysql:5.7
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
      MYSQL_ROOT_PASSWORD: ''

      MYSQL_DATABASE: $DB_NAME
      MYSQL_USER: $DB_USER
      MYSQL_PASSWORD: $DB_PWD

    volumes:
      - mysql:/var/lib/mysql

volumes:
  mysql:

networks:
  default:
    ipam:
      config:
        - subnet: ${SUBNET_DEFAULT}

# vim: ts=2 sts=2 sw=2 et:
