#!/usr/bin/env bash

set -e

if [ -t 0 ]; then
    TTY="Yes"
else
    TTY=
fi

for p in "$@"; do
    [[ "$p" != "-"* ]] && break
    shift
    case "$p" in
        -T) TTY= ;;
        *)
            echo >&2 "Unkown option : '$p'"
            exit 1
    esac
done

CONTAINER_NAME=$1
shift

if [ -f "/.dockerenv" ]; then
    exec "$@"
fi

case "$CONTAINER_NAME" in
    www-api|webadmin-php)
        CONTAINER_TYPE=php
        ;;
    *)
        CONTAINER_TYPE="$CONTAINER_NAME"
        ;;
esac

current_dir=$(realpath "$PWD")
cd $(dirname $0)/..

. .env

declare -a cmd=('docker' 'exec' '-i')

if [ "$TTY" ]; then
    cmd+=("-t")
fi
echo $CONTAINER_NAME
CONTAINER_NAME="$(docker inspect --format '{{.Name}}' $(docker-compose ps -q "$CONTAINER_NAME"))"

if [ "$CONTAINER_TYPE" = "php" ]; then
    cmd+=("-u" "www-data:www-data")
    cmd+=("$CONTAINER_NAME")
    cmd+=("exec-pwd" "$current_dir")
else
    cmd+=("$CONTAINER_NAME")
fi

echo >&2 "# ${cmd[@]} $@"
exec "${cmd[@]}" "$@"

# vim: ts=4 sts=4 sw=4 et:


